### ISSUE TITLE
WatchKitAppBundleIDNotprefixed重签名后无法安装

### ISSUE THREAD

**Issue by maltsugar** [yohunl/DingTalkNoJailTweak#1]
iTools 提示错误：WatchKitAppBundleIDNotprefixed

**Comment by maltsugar** [comment]
删掉包里的.app里的 Watch文件夹， 可以安装，打开又闪退。 大家是怎么解决的呢

**Comment by yohunl** [comment]
首先,你要删掉watch相关文件夹
其次,如果安装后,打开就闪退,那么多半是签名问题

**Comment by maltsugar** [comment]
嗯 试了好多方法，之前删掉watch文件夹会闪退。 又去Google了， 修改了watch里面所有的bundleid 为自己的bundleid  始终无法安装。后来又自己创建项目，添加watchkit，archive后替换 watch，也不行。最后准备放弃，又删掉watch文件夹试了下，突然又行了。

感谢博主分享技术，无私奉献，学到不少东西

**Comment by yohunl** [comment]
watch,因为签名和本主是不一致的,所以,需要删除后,重签名的,才能在机器上安装,
解决问题了就好,🙃
