### ISSUE TITLE
不能登录呀

### ISSUE THREAD

**Issue by HolmesZhao** [yohunl/DingTalkNoJailTweak#5]

**Comment by HolmesZhao** [comment]
登录的时候提示我 “param invalid ”

**Comment by AemonChan** [comment]
可以用，我成功了。公司要打卡，我淘宝买了签了名。以后就用它了，

**Comment by Xcode1994** [comment]
安装好像提示 app watch bundle 不对是为什么


只要删掉 watch文件夹就可以了,是因为watch的我们重签不了

**Comment by Xcode1994** [comment]
的确登录的时候提示 “param invalid ”

**Comment by yohunl** [comment]
这个是钉钉做了检测,你重签名时候,不要修改bundle id就可以了
