### ISSUE TITLE
logify Tweak.xm

### ISSUE THREAD

**Issue by piaojin** [yohunl/DingTalkNoJailTweak#6]
你好,我利用logify 给某个类加上了打印信息,但是里面包含其他的类,make时会报找不到这个类,我看了你的Tweak.xm文件,有些地方是用NSObject替换其他类,有些是用id替换其他类,能普及一下关于这类问题吗?谢谢 by 逆向小菜!

**Comment by yohunl** [comment]
这个,用id或者NSObject都可以,只要让它不报错就可以了

**Comment by piaojin** [comment]
嗯嗯，突然傻了一下，OC的函数只与函数名有关，与参数的类型无关，所以参数类型改成id或者NSObject都可以覆盖掉原来的函数！谢谢了！
