### ISSUE TITLE
登录提示非官方客户端

### ISSUE THREAD

**Issue by kevieYu** [yohunl/DingTalkNoJailTweak#7]
踢出到登录页面，是签名的问题吗？

**Comment by yohunl** [comment]
你是不是更改了bundle id?

**Comment by Musk66** [comment]
如果非越狱机的话不改bundleid就没法弄了，申请证书的时候用正版的bundleid肯定弄不下来啊

**Comment by Musk66** [comment]
打算搜头文件里用到bundleid的位置都给篡改下
