### ISSUE TITLE
安装成功后没法登录

### ISSUE THREAD

**Issue by xiaofu666** [yohunl/DingTalkNoJailTweak#9]
这个我安装上去后 , 有个弹框提示说 这个不是钉钉官方应用,已禁止登陆,请下载官方正版应用!有什么办法修改吗?

**Comment by dannyZhou** [comment]
应该是有 bundle id 自校验

**Comment by dannyZhou** [comment]
Please see all closed issues in this project.

**Comment by YangsCalvin** [comment]
加一段代码就OK 
%hook DTInfoPlist
+ (NSString *)getAppBundleId{
	return @"com.laiwang.DingTalk";
}
%end

**Comment by yohunl** [comment]
楼上正解
